### ISSUE TITLE
Rewrite in Solidity and Rust (🚀)

### ISSUE THREAD

**Issue by ghost** [nedoxff/british_quiz#1]
Clearly the future is Web Three and it must be Decentralised. Also consider making every asset an NFT for maximum decentralisa--

> "Hey, where's my apes?"
> \- "us-west-1 is down. We're working on it."
> "But I thought it was decentralised?"
> \- "It's actually much better than that. We've taken decentralised finance and centralised it, offering all the benefits of CeFi and DeFi. We call it centralised decentralised finance, or CeDeFi for short."
> ["This is a joke, right?"](https://www.google.com/search?q=cedefi)

**Comment by nedoxff** [comment]
sorry, bbut this is only planned for the next milesotne (2.0), so i mujst close the issue >~~~<
